server:
  port: 9090
  error:
    include-stacktrace: never
    include-binding-errors: never


spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/metadata_db?autoReconnect=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
